"""
LLM-Powered Report Generator

Generates natural language fraud reports using Groq/OpenAI API.
Uses the existing report data and enhances it with AI-generated summaries.

Author: FinSight AI
"""

import os
from typing import Any, Optional
from groq import Groq

from app.utils.logging import api_logger


class LLMReportGenerator:
    """Generate natural language fraud reports using LLM."""

    def __init__(self):
        """Initialize LLM client (Groq)."""
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            api_logger.warning("GROQ_API_KEY not found. LLM report generation will be disabled.")
            self.client = None
        else:
            self.client = Groq(api_key=api_key)
        
        self.model = os.getenv("LLM_MODEL", "llama-3.1-8b-instant")

    def generate_fraud_summary(
        self,
        risk_score: float,
        is_fraud: bool,
        detected_issues: list[str],
        key_metrics: dict[str, Any],
        document_name: str,
    ) -> str:
        """
        Generate natural language summary of fraud analysis using LLM.

        Args:
            risk_score: Combined risk score (0-100)
            is_fraud: Fraud verdict
            detected_issues: List of flagged issues
            key_metrics: Transaction statistics
            document_name: Name of analyzed document

        Returns:
            Natural language summary generated by LLM
        """
        if not self.client:
            return self._fallback_summary(risk_score, is_fraud, detected_issues)

        prompt = self._build_prompt(
            risk_score, is_fraud, detected_issues, key_metrics, document_name
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a financial compliance expert analyzing bank statements for fraud. "
                            "Generate concise, professional summaries highlighting risk factors and recommendations. "
                            "Use clear, actionable language suitable for compliance officers."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,  # Low temperature for consistent, factual output
                max_tokens=500,
            )

            return response.choices[0].message.content.strip()

        except Exception as e:
            api_logger.error(f"LLM report generation failed: {e}")
            return self._fallback_summary(risk_score, is_fraud, detected_issues)

    def generate_recommendation(
        self,
        risk_score: float,
        is_fraud: bool,
        detected_issues: list[str],
    ) -> str:
        """
        Generate AI-powered compliance recommendation.

        Args:
            risk_score: Risk score (0-100)
            is_fraud: Fraud verdict
            detected_issues: List of flagged patterns

        Returns:
            LLM-generated recommendation
        """
        if not self.client:
            return self._fallback_recommendation(risk_score, is_fraud)

        safe_score = max(0.0, min(100.0, float(risk_score)))
        if safe_score >= 70:
            risk_band = "HIGH"
        elif safe_score >= 45:
            risk_band = "MEDIUM"
        else:
            risk_band = "LOW"

        prompt = f"""Based on this fraud analysis:

- Risk Score: {risk_score}/100
- Risk Band: {risk_band}
- Fraud Detected: {'YES' if is_fraud else 'NO'}
- Flagged Issues: {len(detected_issues)}

Issues:
{chr(10).join(f'- {issue}' for issue in detected_issues[:5])}

Generate a specific, actionable recommendation for compliance officers.
Include:
1. Action urgency based on risk band
2. Specific next steps (verification, investigation, monitoring)
3. Timeline for action

Severity policy (must follow):
- HIGH: may use urgent language and immediate manual review.
- MEDIUM: do NOT use urgent/immediate language; recommend enhanced monitoring and targeted review.
- LOW: no immediate action required.

Keep it under 100 words."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a senior compliance officer providing actionable fraud prevention recommendations.",
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.2,
                max_tokens=200,
            )

            return response.choices[0].message.content.strip()

        except Exception as e:
            api_logger.error(f"LLM recommendation failed: {e}")
            return self._fallback_recommendation(risk_score, is_fraud)

    def _build_prompt(
        self,
        risk_score: float,
        is_fraud: bool,
        detected_issues: list[str],
        key_metrics: dict[str, Any],
        document_name: str,
    ) -> str:
        """Build detailed prompt for LLM summary generation."""
        return f"""Analyze this financial document fraud assessment:

**Document:** {document_name}
**Risk Score:** {risk_score}/100
**Fraud Verdict:** {'FRAUDULENT ACTIVITY DETECTED' if is_fraud else 'No fraud detected'}

**Transaction Metrics:**
- Total Transactions: {key_metrics.get('total_transactions', 0)}
- Total Debited: ${key_metrics.get('total_debited', 0):,.2f}
- Total Credited: ${key_metrics.get('total_credited', 0):,.2f}
- High-Risk Merchants: {key_metrics.get('high_risk_merchants', 0)}
- Max Transaction: ${key_metrics.get('max_transaction_amount', 0):,.2f}
- Rapid Transactions: {key_metrics.get('rapid_transactions', 0)}

**Detected Issues:**
{chr(10).join(f'{i+1}. {issue}' for i, issue in enumerate(detected_issues[:10]))}

Generate a professional 3-paragraph summary:
1. Overall risk assessment
2. Key red flags and patterns
3. Recommended action

Keep it factual, concise, and actionable for compliance review."""

    def _fallback_summary(
        self, risk_score: float, is_fraud: bool, detected_issues: list[str]
    ) -> str:
        """Fallback summary when LLM is unavailable."""
        verdict = "fraudulent activity detected" if is_fraud else "no fraud detected"
        return (
            f"This analysis identified a risk score of {risk_score}/100 with {verdict}. "
            f"{len(detected_issues)} suspicious patterns were flagged. "
            f"{'Immediate manual review is recommended.' if is_fraud else 'Standard monitoring procedures apply.'}"
        )

    def _fallback_recommendation(self, risk_score: float, is_fraud: bool) -> str:
        """Fallback recommendation when LLM is unavailable."""
        if is_fraud and risk_score >= 70:
            return "URGENT: Manual compliance review required. Consider account suspension pending investigation."
        elif is_fraud:
            return "Manual review required. Enhanced monitoring and verification recommended."
        elif risk_score >= 45:
            return "Enhanced monitoring recommended. Track for trend analysis."
        else:
            return "No immediate action required. Continue standard procedures."


# Singleton instance
_llm_generator: Optional[LLMReportGenerator] = None


def get_llm_report_generator() -> LLMReportGenerator:
    """Get or create singleton LLM report generator."""
    global _llm_generator
    if _llm_generator is None:
        _llm_generator = LLMReportGenerator()
    return _llm_generator
